"""Gravitational time dilation simulation and inference library."""

from clocks.api import build_particle_filter, infer, simulate, simulate_and_infer
from clocks.config import InferenceConfig, NoiseConfig, PriorConfig, SimulationConfig
from clocks.inference import (
    ConvergenceInfo,
    Estimate,
    ModelComparison,
    ModelComparisonResult,
    ParticleFilter,
)
from clocks.noise import (
    add_clock_noise,
    log_likelihood_gaussian,
    log_likelihood_gaussian_batch,
)
from clocks.physics import (
    clock_rates,
    clock_rates_batch,
    clock_rates_batch_multi,
    clock_rates_density_gaussian,
    clock_rates_density_gaussian_batch,
    compute_distances,
    gravitational_potential,
    time_dilation_factor,
)
from clocks.results import (
    HistoryEntry,
    InferenceResult,
    ModelComparisonInferenceResult,
    SimulationResult,
)
from clocks.types import ClockArray, MassConfig, Observation, ParticleState
from clocks.viz import (
    animate_echolocation,
    animate_inference,
    animate_inference_2d,
    animate_inference_multi_1d,
    animate_inference_multi_2d,
    animate_model_comparison,
    create_echolocation_dashboard,
    create_inference_dashboard,
    plot_centered_rates,
    plot_clock_rates,
    plot_clock_rates_2d,
    plot_clock_setup,
    plot_clock_setup_2d,
    plot_mass_histogram,
    plot_particle_cloud,
    plot_particle_cloud_2d,
    plot_particle_cloud_multi_1d,
    plot_particle_cloud_multi_2d,
    plot_scene_3d,
)

__all__ = [
    "ClockArray",
    "ConvergenceInfo",
    "Estimate",
    "HistoryEntry",
    "InferenceConfig",
    "InferenceResult",
    "MassConfig",
    "ModelComparison",
    "ModelComparisonInferenceResult",
    "ModelComparisonResult",
    "NoiseConfig",
    "Observation",
    "ParticleFilter",
    "ParticleState",
    "PriorConfig",
    "SimulationConfig",
    "SimulationResult",
    "add_clock_noise",
    "animate_echolocation",
    "animate_inference",
    "animate_inference_2d",
    "animate_inference_multi_1d",
    "animate_inference_multi_2d",
    "animate_model_comparison",
    "build_particle_filter",
    "clock_rates",
    "clock_rates_batch",
    "clock_rates_batch_multi",
    "clock_rates_density_gaussian",
    "clock_rates_density_gaussian_batch",
    "compute_distances",
    "create_echolocation_dashboard",
    "create_inference_dashboard",
    "gravitational_potential",
    "infer",
    "log_likelihood_gaussian",
    "log_likelihood_gaussian_batch",
    "plot_centered_rates",
    "plot_clock_rates",
    "plot_clock_rates_2d",
    "plot_clock_setup",
    "plot_clock_setup_2d",
    "plot_mass_histogram",
    "plot_particle_cloud",
    "plot_particle_cloud_2d",
    "plot_particle_cloud_multi_1d",
    "plot_particle_cloud_multi_2d",
    "plot_scene_3d",
    "simulate",
    "simulate_and_infer",
    "time_dilation_factor",
]
